FROM ubuntu
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y git
RUN apt-get install -y python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install celery==4.4.7
RUN git clone https://github.com/TabeaHaverkamp/ACC-Project-BENCHOP.git
